### ISSUE TITLE
is there a way to allow the home app to show a target temp of less than 50 degrees F?

### ISSUE THREAD

**Issue by pponce** [senorshaun/homebridge-nuheat#1]
When my nuheat thermostat is set to 42 degrees F the home app shows that it is set to 50.
When i turn debug on the nuheat debug message shows the correct target temperature of 5.7°C (42°F)
[NuHeat] Target temperature for Bathroom is 5.7°C
[NuHeat] Current temperature of Bathroom is 21.3°

But the home app seems to have a min of 50 that it allows me to set and also to report back on.
Anyway to adjust this?

Thanks for putting this plugin together.

**Comment by senorshaun** [comment]
Sorry for the late response but if I remember correctly, that is HomeKit that has a 50 degree floor. The only temp thing I do is convert teh NuHeat temp in to Celsius. Nuheat shows weird stuff in the API so the math for that is (((nuHeatTemp -33)/56)+33)-32)*5/9)

**Comment by pponce** [comment]
Thanks for following up.
I'm a bit OCD about these things so i just changed my settings to set to 50 since the original 41 setting was just my OFF temp.  Strange that it would not be configurable per device.
