### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by RichardSaouma** [senorshaun/homebridge-nuheat#10]
Not sure how to handle this as I have not seen errors like this before.... any advice?

TypeError: Cannot read properties of undefined (reading 'map')
    at NuHeatAPI.trimSetCookie (/var/lib/homebridge/node_modules/homebridge-nuheat/lib/NuHeatAPI.js:552:26)
    at NuHeatAPI.getOAuthToken (/var/lib/homebridge/node_modules/homebridge-nuheat/lib/NuHeatAPI.js:292:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NuHeatAPI.acquireAccessToken (/var/lib/homebridge/node_modules/homebridge-nuheat/lib/NuHeatAPI.js:431:23)
    at NuHeatPlatform.setupPlatform (/var/lib/homebridge/node_modules/homebridge-nuheat/index.js:44:9)
[23/04/2023, 10:18:48] Got SIGTERM, shutting down Homebridge...

**Comment by zellunit** [comment]
@RichardSaouma i am getting the same thing. not only does nuheat fail but when it does it crashes my entire homebridge. did you find a fix for this? feels like the api changed on nuheats end but this plugin is still assuming the old format.

**Comment by RichardSaouma** [comment]
Yes I was able to resolve it, the two steps taken were:
(1) factory reset the nuheat and pairing it anew to the WiFi 
(2) registering the nuheat thermostat anew under a different email than before

hope this helps!

**Comment by zellunit** [comment]
@RichardSaouma thanks for the fast reply. albeit that sounds like a very inconvenient fix. i have 4 of these each with different complex schedules. and all 100+ other general devices in my home are under the same email so having a one off here for this is just a bummer.

@senorshaun is there any proper fix pending perhaps? curious if other users are seeing this.

**Comment by RichardSaouma** [comment]
@zellunit some potential pointers: the Nuheat portal is a touch archaic.. I did not try, but it might work for you (i.e. if using a gmail address) to add an arbitrary period in the address--I suspect Nuheat may view it as new, though it will obviously come still land in your inbox provided your provider enables this (gmail does).

Before moving to homebridge, I was using IFTTT for Nuheat automation--there might be another way to connect to your units via IFTTT to whatever client-side software you use (e.g. I use homekit and homebridge now, but still maintain the IFTTT connection, so as to merge with my outlook calendar).

Fingers crossed!

**Comment by gianlucad3** [comment]
I'm seeing the same issue. @RichardSaouma are you suggesting creating a new account w/ the new email address or simply modifying the email in the existing account? Thanks.

**Comment by RichardSaouma** [comment]
I would try the easiest one first… register anew with the “.” On your email ahead of the “@“, if that fails then I think the only way to make it work would be to register a new email address (new to nuheat). It’s annoying but once you commit to tearing off the bandaid, it’s relatively quick.

Richard Saouma
***@***.***
________________________________

**Comment by senorshaun** [comment]
Sorry I've been away for a bit. It looks like NuHeat isn't seeing the clientID (homebridge-nuheat) as authorized to try to oauth for accounts anymore. Since that step (where it tries to get an auth token to then use for login) is before any credentials login, I'm not sure how changing the email address would be working?
I've reached out to nuheat about the issue, and in the mean time have pushed 1.1.4 which handles not getting a token, and just retrying in a bit (based on the refresh period set in your config which defaults to 60 seconds). That will keep homebridge from crashing, and also allow the plugin to initialize itself properly whenever nuheat gets around to responding to me and re-enabling the clientID

**Comment by senorshaun** [comment]
Fixed in 1.2.0
