### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by StefanCioata** [senorshaun/homebridge-nuheat#12]
Homebridge Nuheat (homebridge-nuheat v1.1.4)

Homebridge logs...
[5/21/2023, 4:43:09 PM] [NuHeat] NuHeatAPI: Unable to access the OAuth authorization endpoint.
[5/21/2023, 4:43:09 PM] [NuHeat] Unable to acquire an access token. We will try again later.

... and it tries unsuccessfully many times

{
            "name": "NuHeat",
            "email": "st.cioata@gmail.com",
            "password": "password",
            "devices": [
                {
                    "serialNumber": "SN#01"
                },
                {
                    "serialNumber": "SN#02"
                },
                {
                    "serialNumber": "SN#03"
                }
            ],
            "platform": "NuHeat"
        }

Any help will be more then welcome! Thank you

**Comment by potterdai** [comment]
Hey there, I made a fork which is using [homeassistant](https://github.com/broox/python-nuheat) version's nuheat API.  https://github.com/potterdai/homebridge-nuheat
It lacks certain functions (such as group, away mode, etc.), but will work for basic temperature setup. Can be used as a work around until Nuheat fixed the homebridge client issue. =)

**Comment by StefanCioata** [comment]
Hi there,

I am pretty new to the whole thing... How do I install your fork? When I
search for "nuheat" I get the package from @senorshaun. I think I need to
add something like:

<script type="module">
import homebridgeMyhomeOwn from '
***@***.***/+esm'
</script>

but I am not sure where. Can you please help ?

Thank you,
Stefan

**Comment by senorshaun** [comment]
Fixed in 1.2.0
