### ISSUE TITLE
broken after homekit architecture upgrade

### ISSUE THREAD

**Issue by devlinandrew** [senorshaun/homebridge-nuheat#15]
Home app interface for the heated floor keeps jumping back to OFF so I cant change the temp.  If I try to move it to HEAT, it just flips back to OFF immediately. I can change temps in Homebridge browser UI without issue.  Could this be a hub/AppleTV issue rather than the plugin?  Thanks!

**Comment by senorshaun** [comment]
Anything in the logs?

**Comment by devlinandrew** [comment]
Seems to have resolved itself after disconnecting one Apple TV from ethernet.  so weird, but a fix is a fix.  

If I connect the offending Apple TV to ethernet, all Homebridge devices go "No Response" in the Home app...if I disconnect and switch to WiFi, they all work again.

Closing the issue as initially raised.

**Comment by senorshaun** [comment]
Is that Apple TV maybe becoming the home hub when on Ethernet? And it could be running  older or beta version of tvOS? Just guessing

**Comment by devlinandrew** [comment]
Same tvOS version and hardware generation of Apple TV as 2 more in my house.  It's super odd, really.  Maybe I need to reset it and restore it.
