### ISSUE TITLE
Is the NuHeat API down?

### ISSUE THREAD

**Issue by drewmacneil** [senorshaun/homebridge-nuheat#16]
I've noticed for the last few days that my `homebridge-nuheat` installation (`v1.2.2`) is cycling through the following logs:

```
[4/6/2024, 8:03:35 PM] [NuHeat] Trying to refresh thermostats.
[4/6/2024, 8:03:35 PM] [NuHeat] NuHeatAPI: Acquiring new access token. Ours seems to be missing
[4/6/2024, 8:03:36 PM] [NuHeat] NuHeatAPI: Successfully connected to the NuHeat API.
[4/6/2024, 8:03:36 PM] [NuHeat] NuHeatAPI: NuHeat had an internal server error.
[4/6/2024, 8:03:36 PM] [NuHeat] NuHeatAPI: Trying again.
[4/6/2024, 8:03:36 PM] [NuHeat] NuHeatAPI: NuHeat had an internal server error.
[4/6/2024, 8:03:36 PM] [NuHeat] Error getting data from NuHeatAPI in thermostat refresh
```

I then tried using a Postman-like tool to connect directly to the [NuHeat API](https://api.mynuheat.com/) using the OAuth credentials that `homebridge-nuheat` uses and get the following response, irrespective of which API endpoint I invoke:

```
{
  "Messages": [
    "Internal Server Error."
  ]
}
```

I couldn't find a status page for the API, so I thought I'd post here to see if others are experiencing the same thing.

**Comment by WillFulmer** [comment]
Seeing same issue here:

<img width="790" alt="image" src="https://github.com/senorshaun/homebridge-nuheat/assets/36053224/8a83a4db-e832-4591-b212-f79213f07c7a">

**Comment by devlinandrew** [comment]
I wonder if Nuheat went the MyQ route...

**Comment by drewmacneil** [comment]
I switched to [this fork](https://github.com/potterdai/homebridge-nuheat), which seems to be working in the meantime. It appears to use a different API than the publicly documented one.

**Comment by hmangnx** [comment]
Yeah I am seeing the same issue. I installed the fork version and that seems to work. But the away mode button doesn’t seem to show.

**Comment by hmangnx** [comment]
Everything seems to be fixed now. I believe this was an issue on nuheat’s side as even ifttt wasn’t working at that time.

**Comment by senorshaun** [comment]
I agree. I'm just now getting around to a computer but I'm seeing things log in properly
