### ISSUE TITLE
Question on how to access thermostats using this plugin

### ISSUE THREAD

**Issue by GitHubRR1867** [senorshaun/homebridge-nuheat#3]
Hi-  I’ve installed this plugin and updated my config file with my correct credentials, but after homebridge logs into “nuheat” it tells me “0 devices added.”  So I’m not able to connect with my nuheat thermostat.  Any thoughts realty appreciated.

**Comment by senorshaun** [comment]
can you send me your config?

**Comment by senorshaun** [comment]
stale
