### ISSUE TITLE
Update plans?

### ISSUE THREAD

**Issue by hjdhjd** [senorshaun/homebridge-nuheat#5]
Appreciate the plugin…it does a great job overall at achieving it’s goal. That said, I’d suggest that it really needs to be modernized for more recent Homebridge releases to improve responsiveness and take advantage of some of the newer asynchronous Homebridge capabilities.

Any plans to modernize / refactor the plugin? If not, I’d be interested in taking over the project if this isn’t an area of interest any longer. I have several Homebridge plugins with substantial user bases (homebridge-myq and homebridge-unifi-protect), and I’ve got a vested interest in this one given I use it. 😄 

Again - appreciate the work you put in to create this in the first place. I’d love to evolve it further if you don’t intend to.

**Comment by ankaerith** [comment]
As a user of both this plugin and homebridge-unifi-protect, I'd love to see @hjdhjd contribute or carry the torch forward.  @senorshaun thoughts?

**Comment by senorshaun** [comment]
@hjdhjd not sure how I missed this issue when you first posted, sorry about that. I had some time over the weekend, and got approved for api access by nuheat, so I updated the plugin to 1.1.0. it uses the new api, adds in away mode switches for groups (auto-detect option), adds an auto-detect option for thermostats (for most people who only have one house, this is ideal), customize the hold length time i.e. till next scheduler event, X minutes, or permanent. I've tested quite a bit, today lol, please file a new issue if you find any. note: nuheat says that they are doing signalr notifications, which would be much better than polling, but I don't receive any. I've reach out to them about it. the plugin registers for them, and does all the logic should it get them. if any changes need to be made I'll do a 1.1.1 update
