### ISSUE TITLE
Plug-in works in Homebridge/browser, but not in Home app

### ISSUE THREAD

**Issue by devlinandrew** [senorshaun/homebridge-nuheat#7]
I've configured the plugin with all defaults (no thermostats specified, it pulls them in automatically).  I am able to control the temps via HomeBridge in the browser perfectly, but I can't take any actions in the Home app. 

I have tried in a child bridge and in classic mode. 

For example, the thermostat shows in the Home App, but if I try to change the temp, it just snaps back to the current temp immediately. There is nothing in the logs on HomeBridge when this happens, so its like the commands aren't making it back to HomeBridge.

This is on an iPhone 13 w/ 16.1 and 3x Apple TV hubs (all hardwired).

**Comment by devlinandrew** [comment]
OK, more testing after I posted this. I have updated to 16.2 on the iPhone and can now change the temperature on the thermostat from the Home app but I can't turn the thermostat off (I still get the snap back behaviour).

**Comment by senorshaun** [comment]
Interesting. Thanks for that info. 
there is no actual off function from what I saw, even on your thermostat. Instead ‘off’ or ‘away’ just sets the setpoint at like 45F, which HomeKit can’t go that low, it goes to like 53F I think. 

Correct me if I’m wrong, I don’t have any NuHeat thermostats myself, I wrote this for a friend.

**Comment by senorshaun** [comment]
Also, there should be a Debug flag you can enable which should spit out a lot of logs

**Comment by devlinandrew** [comment]
I think you're right about not having an "Off" state.  I will switch this to just set it to a low temp rather than using the off state.  Thanks!

**Comment by devlinandrew** [comment]
This can be closed now.  The missing Off state was the issue for me...thanks for the input!
